development:
  adapter: postgresql
  encoding: unicode
  database: proficiency-test_development
  pool: 5
  host: localhost
  port: 5433  
  username: postgres
  password: 1234

test:
  adapter: postgresql
  encoding: unicode
  database: proficiency-test_test
  pool: 5
  username: postgres
  host: localhost
  port: 5433
  password: 1234